apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cvat-opa
spec:
  selector:
    matchLabels:
      app: cvat-opa
  serviceName: "opa"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: cvat-opa # has to match .spec.selector.matchLabels
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: cvat-opa
        image: guenltu/private:fla-cvat-opa
        ports:
        - containerPort: 8181
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: opa
spec:
  ports:
  - port: 8181
    name: http
  selector:
    app: cvat-opa
